---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dply4
  labels:
    app: beauty
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      minunavailable: 2
  selector:
    matchLabels:
      app: beauty
  template:
    metadata:
      name: tmplt1
      labels:
        app: beauty
    spec:
      containers:
        - name: con1
          image: apsanadevops/beauty:jewels
          ports:
           - containerPort: 80
...
